### ISSUE TITLE
Change definition phoneme

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#110]
Current definition of phoneme is **A speech sound that is distinguished by the speakers of a particular language.**

What constitutes a phoneme is specific to a given language, this is not so clear in the current definition, but more importantly, a phoneme is not any speech sound that is distinguished, but the smallest unit that can be used to distinguish. The current definition would also include syllables or even whole words.

I suggest we replace it with the following definition: **Any of the minimally distinct units of sound in a specified language that distinguish one word from another.**

**Comment by VisLab** [comment]
@smakeig

**Comment by VisLab** [comment]
Google says:
> Phonemes are the meaningfully different sound units in a language (the smallest units of sound).

People ask:
> "phoneme, in linguistics, smallest unit of speech distinguishing one word (or word element) from another, as the element p in “tap,” which separates that word from “tab,” 

Which came from:  [Britannica.com](https://www.britannica.com/sitemap/p/95)

@monique @smakeig can we move forward.

**Comment by VisLab** [comment]
Addressed in PR #140
