### ISSUE TITLE
Change definition syllable 

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#111]
Current definition of syllable is **A unit of spoken language larger than a phoneme.**

A syllable can be one phoneme, it is not necessarily larger than a phoneme.

I suggest we replace it with: **A unit of pronunciation having a vowel or consonant sound, with or without surrounding consonants, forming the whole or a part of a word.**

**Comment by VisLab** [comment]
@smakeig

**Comment by VisLab** [comment]
Incorporated in PR #140

**Comment by VisLab** [comment]
Addressed in PR #140
