### ISSUE TITLE
Nonword: commonly used to refer to an unpronounceable string

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#113]
The concept of nonword is not very clear in psycholinguistic research. It is occasionally for how it is defined in HED: **A group of letters or speech sounds that looks or sounds like a word but that is not accepted as such by native speakers.** But frequently it is also used to refer to completely unpronounceable strings. The more common word for letters or speech sounds that are pronounceable in a language but not associated with meaning is *pseudoword*.

Maybe it is possible to add pseudoword as a synonym in some way. I think the use of nonword as it is in the schema will be confusing for many researchers who are interested in this concept, both during annotation and search.

**Comment by VisLab** [comment]
This sounds reasonable...can you make a specific proposal?   Pseudoword sounds like a good thing to add -- but should we keep Nonword as something that cannot be pronounced?   What would the two look like and where would they go?

**Comment by monique2208** [comment]
I think adding pseudoword with the current definition is a good idea. 

I am uncertain about nonword for two reasons:
1. Sometimes it is used in the same way as pseudoword, also in literature, so there may be some people who confuse this. With pseudoword I have never seen another definition. 
2. Changing the definition of Nonword would break previous annotations. We have some datasets annotated, here we have followed the HED definition as I assume other people would have done. The other definition changes I suggested are improvements, but they do not change the concept behind the term, but this would and I am not sure how this would work with different versions of HED. 

It would be nice to have a term for an unpronouncable letter string. But while pseudoword can easily go under units, such a string is more complex. Most units are independent of form. A word has a written and spoken form, and even though phoneme and grapheme seem form specific grapheme can be mapped to sounds and phonemes can be mapped to writing (although it is not a one to one mapping). But in the end I think it is okay to have some units that are form specific and this might be one of them.

**Comment by VisLab** [comment]
@monique2208 could we help come to a resolution on this for the next release of the schema?

**Comment by smakeig** [comment]
I suggest the possibility that the term 'word/#' take labels including 'pronounceable|unpronounceable', 'actual|pseudo', ...  -

**Comment by VisLab** [comment]
@monique2208 Can you propose a specific change:
Tag:  
Parent:  
Description:  
Attributes:  

@smakeig  `Word` is not a tag that takes a #.  The labels are reasonable.  The question is are we going to add this or not?

@monique2208  Users could extend `Word` as  `Word/Non-word`.

**Comment by monique2208** [comment]
Word is currently understood and defined as an existing word: something with semantic and functional content. Having non word as a subcategory would break this definition, and previous annotations and even with an updated definition, it is very unlikely that people will not default to using the Word tag in the way that the concept of a word is commonly understood. 

Could we have simply add a pseudoword tag that is the same as nonword. So the old non word tag would still work but people will find and can use the uncontroversial pseudoword instead in the future? I think an unpronouncable letter string should be a separate item that could be added to the schema or in the language schema. It could simply be Unpronouncable-letter-string.

Tag: Pseudoword
Parent: Language-item
Description: A group of letters or speech sounds that looks or sounds like a word but that is not accepted as such by native speakers.
Attributes: ?

**Comment by VisLab** [comment]
We should probably deprecate Non-word

**Comment by monique2208** [comment]
I think that would be a good solution because I think it adds some confusion, and I think we can cover both the unpronouncable letter string, as well as the pronouncable letter string with better, more universally understood terms.

**Comment by smakeig** [comment]
I have seen the usage:

word = word ...
pseudoword = pronouncable nonword
nonword = unpronouncable nonword - or any nonword string...

**Comment by VisLab** [comment]
Addressed in PR#140.
