### ISSUE TITLE
Missing label 'Left' and 'Right' as Property

### ISSUE THREAD

**Issue by dorahermes** [hed-standard/hed-schemas#137]
In the current HED schema library, there is no 'Left' and 'Right' as a Property, only as a relation. Now, this created issues when trying to describe doing something with your left or right hand. 

Currently, your left hand would be described as `(Hand, (Left-side-of, Body))`, now this creates obvious issues because your left hand is not always on the left of your body, and creates obvious issues if you want to describe the task instruction 'touch your right ear with your left hand' (example based on previous input from @smakeig ). 

Another example of when this may creates issues is when the task would be to look from the left to the right. My intuition would indicate that I would use `(Left, (From-to, Right))` but that is invalid, and we'd have to use something much more intricate (note that Rightward is incorrect in this case). 

Therefore, I think that adding 'Left' and 'Right' as Properties would be extremely helpful, probably as a Categorical-level-value (which already includes High and Low).

**Comment by dorahermes** [comment]
As just discussed, `Left` and `Right` would be useful as a `Categorical-location-value`. This section could also include `Superior`, `Inferior`, `Anterior` and `Posterior`.

**Comment by VisLab** [comment]
An example path in the schema would be:

`Property/Data-Property/Data-value/Categorical-value/Categorical-location-value/Left`

**Proposed description:** Pertaining to a thing located on the west side of a body when facing north, for example the left hand or the left hip. (Adapted from the Oxford English Dictionary).

Other terms would be defined similarly.  What I am trying to capture is that it is a category applied to a thing related to a body.
@dorahermes @monique2208 @smakeig @neuromechanist please weigh in.

**Comment by smakeig** [comment]
Left ... related to the left side of an agent body (from the point of view
of the agent) or object (from the point of view of an agent).

thus ... "moves left  (leftward?) in the scene ..."
"box with its left front corner chipped"
"dog with her left front leg bandaged"
...

**Comment by neuromechanist** [comment]
I wonder how this tag would fair with the currently available `Left-side-of`? Also, a similar concern would be that using the `Left` or `Right` tag alone would be ambiguous. 
Should they always be grouped with another tag, and/or should the `Left` tag be an alias for the `Left-side-of` tag?

**Comment by VisLab** [comment]
As with other categorical tags, it is assumed it would be grouped with
another tag:  (Left, Hand).  Currently we tag the left hand as (Hand,
(Left-side-of, Body)).  They would be equivalent I guess.

**Comment by smakeig** [comment]
Perhaps our concern should also be for the uses of Left to modify a noun
('On the Left within [object]) ..."  versus to modify a verb ('Moving
left[ward] in/on ...)

**Comment by neuromechanist** [comment]
Following @dorahermes suggestion:
> As just discussed, Left and Right would be useful as a Categorical-location-value. This section could also include Superior, Inferior, Anterior and Posterior, 

I would suggest also including `medial` and `lateral`.

**Comment by dorahermes** [comment]
Just noting that `(Hand,(Left-side-of, Body))` is not equivalent to `(Left,Hand)`, as you can also hold your right hand on the left side of your body: `((Right,Hand),(Left-side-of, Body))`

**Comment by dorahermes** [comment]
Update after HED-working group meeting: Left ... relating to the left side of an agent body (from the point of view of the agent) or left side of an object (from the point of view of an agent). This pertains to the identity of the agent or thing. HED-spatial relations should be used for relative positions (e.g.).

**Comment by VisLab** [comment]
This is addressed in PR #140.  However, I did not add Medial and Lateral at this time as I could not come up with an "identity" type defintiion.  This needs further discussion.

**Comment by VisLab** [comment]
How about "Identifying" rather than "Describing"?

**Comment by neuromechanist** [comment]
Looking at medlineplus.gov:

**medial**: Medial means toward the middle or center. [source](https://medlineplus.gov/ency/article/002255.htm)
**lateral**: A position away from the midline of the body. [source](https://medlineplus.gov/ency/imagepages/9505.htm)

Comparing these definitions to the one proposed by @smakeig, it seems that using the _toward_ in the definitions would be beneficial.

**Comment by dorahermes** [comment]
This is great, I can also fix several SCORE issues and suggest simple temporal relations like `(Left, (Before, Right)) ` 

When checking this, I noted in the temporal relations that the instruction miss a comma in `After` and `Before`: they state `(A, (Before B))` rather than `(A, (Before, B)) `.

**Comment by dorahermes** [comment]
Another question, I want to add an example of some quantity (e.g. weight/amplitude) being less than a certain value, but can't find how to add the units, how can I add kilogram to: `(Weight, (Less-than, (Weight/30)))`? thanks!

**Comment by VisLab** [comment]
Addressed in PR#149
