### ISSUE TITLE
Add Radius and/or Diameter tags to the schema

### ISSUE THREAD

**Issue by neuromechanist** [hed-standard/hed-schemas#141]
The 2D and 3D shapes (under `Item/Object/Geometric-object`) under the standard schema can (or should) be able to be assigned a size. While there are size attributes (under `Property/Data-property/Data-value/Spatiotemporal-value/Spatial-value/Size`), including `Length`, `Width`, and `Height`, including `Radius` and/or `Diameter` would make describing the `Ellipse`, `Circle`, `Cone` and `Cylinder` tags more clear and straightforward.

**Suggested Ta**g: `Property/Data-property/Data-value/Spatiotemporal-value/Spatial-value/Size/Radius`
**Suggested Definition**: `The distance of the line from the center of an object to its perimeter.`

**Comment by neuromechanist** [comment]
As per HWG discussion, the **suggested definition** is:

`The distance of the line from the center of a circle or a sphere to its perimeter or outer surface, respectively.`

This definition leaves `Ellipse` size out, as Ellipse size could be defined with it major and minor axes.

**Comment by VisLab** [comment]
Addressed by PR#149
