### ISSUE TITLE
Adding artifact tags to HED standard

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#144]
@dorahermes from [PR#140](https://github.com/hed-standard/hed-schemas/pull/140)

> I would like to add the different EEG artifact types to the main HED schema. Would you like me to open a pull request?
> 
> Biological artifacts would include the following:
> 
>     ** Eye-blink-artifact <nowiki>[Example for EEG: Fp1/Fp2 become electropositive with eye closure because the cornea is positively charged causing a negative deflection in Fp1/Fp2. If the eye blink is unilateral, consider prosthetic eye. If it is in F8 rather than Fp2 then the electrodes are plugged in wrong. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Eye-movement-horizontal-artifact <nowiki>[Example for EEG: There is an upward deflection in the Fp2-F8 derivation, when the eyes move to the right side. In this case F8 becomes more positive and therefore. When the eyes move to the left, F7 becomes more positive and there is an upward deflection in the Fp1-F7 derivation. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Eye-movement-vertical-artifact <nowiki>[Example for EEG: The EEG shows positive potentials (50-100 micro V) with bi-frontal distribution, maximum at Fp1 and Fp2, when the eyeball rotated upward. The downward rotation of the eyeball was associated with the negative deflection. The time course of the deflections was similar to the time course of the eyeball movement. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Slow-eye-movement-artifact <nowiki>[Slow, rolling eye-movements, seen during drowsiness. (Source: Beniczky ea 2013, Appendix S7.)]</nowiki>
>     ** Nystagmus-artifact <nowiki>[Source: Beniczky ea 2017, Table 15.]</nowiki>
>     ** Chewing-artifact <nowiki>[Source: Beniczky ea 2017, Table 15.]</nowiki>
>     ** Sucking-artifact <nowiki>[Source: Beniczky ea 2017, Table 15.]</nowiki>
>     ** Glossokinetic-artifact <nowiki>[The tongue functions as a dipole, with the tip negative with respect to the base. The artifact produced by the tongue has a broad potential field that drops from frontal to occipital areas, although it is less steep than that produced by eye movement artifacts. The amplitude of the potentials is greater inferiorly than in parasagittal regions; the frequency is variable but usually in the delta range. Chewing and sucking can produce similar artifacts. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Rocking-patting-artifact <nowiki>[Quasi-rhythmical artifacts in recordings from infants caused by rocking/patting. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Movement-artifact <nowiki>[Example for EEG: Large amplitude artifact, with irregular morphology (usually resembling a slow-wave or a wave with complex morphology) seen in one or several channels, due to movement. If the causing movement is repetitive, the artifact might resemble a rhythmic EEG activity. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Respiration-artifact <nowiki>[Respiration can produce 2 kinds of artifacts. One type is in the form of slow and rhythmic activity, synchronous with the body movements of respiration and mechanically affecting the impedance of (usually) one electrode. The other type can be slow or sharp waves that occur synchronously with inhalation or exhalation and involve those electrodes on which the patient is lying. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Pulse-artifact <nowiki>[Example for EEG: Occurs when an EEG electrode is placed over a pulsating vessel. The pulsation can cause slow waves that may simulate EEG activity. A direct relationship exists between ECG and the pulse waves (200-300 millisecond delay after ECG equals QRS complex). (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** ECG-artifact <nowiki>[Example for EEG: Far-field potential generated in the heart. The voltage and apparent surface of the artifact vary from derivation to derivation and, consequently, from montage to montage. The artifact is observed best in referential montages using earlobe electrodes A1 and A2. ECG artifact is recognized easily by its rhythmicity/regularity and coincidence with the ECG tracing. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Sweat-artifact <nowiki>[Is a low amplitude undulating waveform that is usually greater than 2 seconds and may appear to be an unstable baseline. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** EMG-artifact <nowiki>[Myogenic potentials are the most common artifacts. Frontalis and temporalis muscles (ex..: clenching of jaw muscles) are common causes. Generally, the potentials generated in the muscles are of shorter duration than those generated in the brain. The frequency components are usually beyond 30-50 Hz, and the bursts are arrhythmic. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
> 
> Non-biological artifacts would include the following:
> 
>     ** Power-supply-artifact <nowiki>[50-60 Hz artifact. Monomorphic waveform due to 50 or 60 Hz A/C power supply. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Induction-artifact <nowiki>[Artifacts (usually of high frequency) induced by nearby equipment (like in the intensive care unit). (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Dialysis-artifact <nowiki>[Source: Beniczky ea 2017, Table 15.]</nowiki>
>     ** Artificial-ventilation-artifact <nowiki>[Source: Beniczky ea 2017, Table 15.]</nowiki>
>     ** Electrode-pops-artifact <nowiki>[Brief discharges with a very steep upslope and shallow fall that occur in all leads which include that electrode. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
>     ** Salt-bridge-artifact <nowiki>[Typically occurs in 1 channel which may appear isoelectric. Only seen in bipolar montage. (Source: Beniczky ea 2013, Appendix S7; Beniczky ea 2017, Table 15.)]</nowiki>
> 
>

**Comment by dorahermes** [comment]
Biological artifacts would include the following:

    ** Eye-artifact <nowiki>[]</nowiki> 
        *** Eye-blink-artifact <nowiki>[]</nowiki>
        *** Eye-movement-artifact <nowiki>[]</nowiki>
         **** Horizontal-eye-movement-horizontal-artifact <nowiki>[]</nowiki>
         **** Vertical-eye-movement-artifact <nowiki>[]</nowiki>
         **** Slow-eye-movement-artifact <nowiki>[]</nowiki>
        *** Nystagmus-artifact <nowiki>[]</nowiki>
    ** Chewing-artifact <nowiki>[]</nowiki>
    ** Sucking-artifact <nowiki>[]</nowiki>
    ** Tongue-movement-artifact <nowiki>[]</nowiki>
    ** Rocking-patting-artifact <nowiki>[]</nowiki>
    ** Movement-artifact <nowiki>[]</nowiki>
    ** Respiration-artifact <nowiki>[]</nowiki>
    ** Pulse-artifact <nowiki>[]</nowiki>
    ** ECG-artifact <nowiki>[]</nowiki>
    ** Sweat-artifact <nowiki>[]</nowiki>
    ** EMG-artifact <nowiki>[]</nowiki>
    
Non-biological artifacts would include the following:
    
    ** Line-noise-artifact <nowiki>[]</nowiki>
    ** Induction-artifact <nowiki>[]</nowiki>
    ** Dialysis-artifact <nowiki>[]</nowiki>
    ** Artificial-ventilation-artifact <nowiki>[]</nowiki>
    ** Electrode-pops-artifact <nowiki>[]</nowiki>
    ** Salt-bridge-artifact <nowiki>[T]</nowiki>
    ** Electrode-movement-artifact <nowiki>[]</nowiki>
    
   @neuromechanist @christinerogers Can you tag a couple of others who would be able to provide input on a HED-artifact section? This needs to be added in HED base schema as it applies beyond EEG to fMRI etc

**Comment by neuromechanist** [comment]
@hjhuang-phd at UCF and Daniel Ferris at UF have worked on movement and environment artifacts.
Beth Smith at USC is actively working on infant EEG. I'll reach out to them for input.

**Comment by VisLab** [comment]
Addressed by PR#149

**Comment by VisLab** [comment]
@monique2208 `Non-biological` was retained as a subcategory to better support search generalization for non-biological artifacts as a group.  While it is true that it is possible to search for "Artifact AND NOT Biological",  NOT searches are hard for users. On the HED ontological side we can declare the two subclasses to be disjoint, so I don't think this will be a semantic issue.
