### ISSUE TITLE
[Human] body-part hierarchy

### ISSUE THREAD

**Issue by neuromechanist** [hed-standard/hed-schemas#164]
The Body-part hierarchy under the base schema appears to be predominantly concerned with human anatomy, although it is stated to be any part of an organism. Nevertheless,  the hierarchy could benefit from more detailed and structured categorization, especially for biomechanical studies and sensor placement. Below is a potential revision. Definitions of currently defined tags have been removed for abstraction, and new potential tags have been added in boldface (no tags are removed). This (or a similar hierarchy) will also help provide a pathway for a more precise annotation of surface anatomy, mainly aimed toward sensor placement, which @sjeung, @JuliusWelzel, and I are pursuing.

* Body-part
  * Head
    * Hair
    * Ear
    * Face
      * Cheek, Chin, Eye, Eyebrow, Forehead, Lip, Nose, Mouth, Teeth
  * **Neck** [The part of the body connecting the head to the torso, containing the cervical spine and vital pathways of nerves, blood vessels, and the airway.]
  * Torso
    * Torso-chest
    * Torso-back
    * **Abdomen** [The part of the body between the thorax and pelvis.]
      * Waist, Hip, Buttocks, **Genitalia**
  * Upper-extremity
    * Upper-arm
      * Shoulder
    * Forearm
      * Elbow
    * Hand
      * Wrist, Palm, Knuckles
      * Finger, Index-finger, Little-finger, Middle-finger, Ring-finger, Thumb
  * Lower-extremity
    * **Upper-leg** [Upper part of the leg between hip and knee.]
      * Thigh
    * **Lower-leg** [Part of the leg between the knee and ankle.]
      * Knee, Calf, Shin
    * Foot
      * Ankle, Heel, Instep, Toes, Big-toe, Little-toe
      
CC @dorahermes  and @monique2208 for comments, edits and suggestions.

**Comment by sjeung** [comment]
Thanks Yahya for putting this out. We believe it will be nice to designate it as the library for "placement" field of [Motion-BIDS](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/motion.html) channels.tsv for human motion tracking.

**Comment by JuliusWelzel** [comment]
@neuromechanist, thanks for moving this forward!

@sjeung, I agree, this is something where we can recommend to use HED terms in a future Motion-BIDS release?

**Comment by VisLab** [comment]
Added in 8.3.0 prerelease.
