### ISSUE TITLE
<property> tags used instead of <attribute>

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-schemas#168]
The (legacy?) `<property>` tags were used instead of `<attribute>` for schemaAttributeDefinitions: https://github.com/hed-standard/hed-schemas/blob/bd30aa1035baa6770913880a1b9d2c5dd5c5735e/standard_schema/hedxml/HED8.2.0.xml#L7040

The schema viewer thus unable to parse these fields to display.

**Comment by IanCa** [comment]
Is this not correct?  I have no issue changing the converter if told to, but it's been like this a while.

The viewer can treat them the same as attributes in most senses, that's what the hed-python code does.

https://hed-specification.readthedocs.io/en/develop/03_HED_formats.html#xml-schema-format

**Comment by dungscout96** [comment]
I see, sorry for the misunderstanding. I updated the schema browser accordingly. It should display the properties now.
