### ISSUE TITLE
[LANG] questions about prerelease 1.0.0

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#213]
@monique2208 

First review -- just structural questions?

Burmese -->  maybe under language?

Morphene-type, Free-morpheme-type, Bound-morphene-type  maybe as a subcategory of Morphene-property. Morpheme-function is that also a Morphene property?  

Should various things Morphological go under a Morphological-property?  Also Morphological-position?  is Morphological-property a Language-item-property?

Should there be a Part-of-speech category with all that Pronoun stuff going under it?

**Comment by monique2208** [comment]
Thanks! I had a look at everything, it was a bit easier with the schema viewer. Most of the issues are typos, or in case of the morpheme stuff, I at some point changed morpological property with morpheme property and this was not adjusted in the parent tags. The pronoun had itself as a parent, which was likely a copy paste error. 

I am not sure how I should go about updating these things now?

**Comment by VisLab** [comment]
Do a pull from hed-schemas/develop to make sure your branch is up to date.
Then make the corrections in the Tag.tsv file.  (Don't touch the
EquivalentTo as it is generated).  Do a PR.  Just change the .tsv file.  Do
not edit anything else.  The mediawiki and xml will be regenerated as will
the tsv.  The system reads the information into a common data structure and
then if no errors, writes it out in all formats, cleaning up stuff like
white space.

@IanCa  anything else to add?

**Comment by VisLab** [comment]
The initial prerelease was successful.  Additional reviews will be posted in a new issue
