### ISSUE TITLE
Discussion of score 1.0.0 Library Schema prerelease

### ISSUE THREAD

**Issue by dorahermes** [hed-standard/hed-schemas#24]
We just made a prerelease of the HED SCORE library schema. This library translates the [SCORE standard](https://www.sciencedirect.com/science/article/pii/S1388245717309069) to HED such that it can easily be used within the Brain Imaging Data Structure [(BIDS)](https://bids-specification.readthedocs.io/en/stable/99-appendices/03-hed.html).

The schema library can be browsed here: 
https://www.hedtags.org/display_hed_score_prerelease.html
(viewer generated from [this mediawiki file](https://github.com/hed-standard/hed-schema-library/blob/main/library_schemas/score/prerelease/HED_score_1.0.0.mediawiki))

If interested, see here for documentation re schema libraries: https://hed-schema-library.readthedocs.io/en/latest/index.html

Comments and suggestions are very welcome!

@tpatpa @VisLab @dungscout96

**Comment by tpatpa** [comment]
HED-SCORE library schema 1.0.0 was [released](https://github.com/hed-standard/hed-schemas/pull/54).
