### ISSUE TITLE
HED online tools version 8.3.0

### ISSUE THREAD

**Issue by ManuelaJaeger** [hed-standard/hed-schemas#283]
Dear HED developers,

I am using the HED online tools for HED annotating German speech stimuli. Thank you that it can also handle german special characters now. In an earlier version the assembled (expanded) event file contained the event onset information in one column "onset" and the HED string in another column "HED_assembled". Now the event onset column is gone and every time two events take place at the exact same time onset the online tool puts both strings after each other in the same line. How can I force the online tool to give me onset and HED annotations for each event individually? It would be easier to share the stimulus information later. 

Thank you,
Manuela

**Comment by VisLab** [comment]
We have to combine all of the events that happen at the same time into a single annotation. for the assembly.  I don't think it is possible to separate them as they have to be taken as a whole. HED events that happen at the same time are not ordered from HED's perspective and any reordering of the events for a particular time is equivalent.  

I think the onset column was removed in the last release.  We can put an option to include it in the next release if you find it useful.

**Comment by ManuelaJaeger** [comment]
Hi,
having the onset information as an option would be great. In our case, we aim for sharing the speech stimulus annotation on a fine grained level (words, phonemes). More than 1000 events per minute. In general this onset information is not part of the original neural data but needs to be added to the data after the data recording during the analysis step. In our case it would be very important to have all important information combined in one file. We would have the onset information to import markers in the neural data and corresponding HED strings for the full description of the presented speech stimulus. This would allow a better reproducibility of findings given the same stimulus material.  Do you know when the next release is planned?  Best regards, Manu

**Comment by VisLab** [comment]
I will try to make sure that something is up on https://hedtools.org/hed_dev by the end of the week.

BTW, if you make sure that each "event" is in parentheses, it should be fairly easy to write a script to expand them to separate lines.  We can eventually do a remodeling operation (the counterpoint to merging) to do that.

**Comment by VisLab** [comment]
This is being implemented in hed-standard/hed-web#240.  The behavior is:

That there will be a `Append assembled` option for both the assemble and search operations for events.  If selected, the assembled HED will be appended to the original events file under the column name "HedAssembled".  The reason that the appending to the onset column was originally removed is that HED now can assemble annotations for any tsv files that follow the BIDS tsv/json model.  There no longer has to be an onset column and it was decided that allowing the users to select columns, while possible was unnecessarily complicated.  I hope this change will be useful.

Please note that this probably won't be propagated to the online tools until next week as there are some other updates that need to be done.

**Comment by ManuelaJaeger** [comment]
Hi, thank you for your help. We finally decided to share the stimulus annotation based on the event.tsv and json file. Additionally, I wrote a short Matlab script to expand the onset merged HED strings to separate lines based on the parentheses. This worked out well. Best, Manu
