### ISSUE TITLE
Difference Clockface and Clock-face

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#44]
I am not entirely sure what the difference between these terms is. Clockface is a 2D object, Clock-face is a Device/Clock. Their definitions are somewhat different but overlap. 

Clockface: The dial face of a clock. A location identifier based on clockface numbering or anatomic subregion.
Clock-face: A location identifier based on clockface numbering or anatomic subregion.

It seems when showing an image of a clock I should use Clockface, but although the image is 2D, the object I show is not, and I am showing a picture of the device.

**Comment by VisLab** [comment]
@monique2208 @makeig  Can we come up with a concrete way of handling this.  We need to clarify the definitions or maybe deprecated Clockface 2D object.

**Comment by monique2208** [comment]
Yes, I think that would solve the problem as well

**Comment by VisLab** [comment]
This has been incorporated into the 8.3.0 prerelease.
