### ISSUE TITLE
Schema viewer attribute display mistitled

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#47]
When the schema viewer is in collapsed mode, none of the auxiliary items can be displayed (like the Unit class definitions).

When the schema viewer is in expanded mode, the auxiliary items are displayed, but
the title is */Relation?temporal-relation/Waiting-for*

@dungscout96

**Comment by dungscout96** [comment]
I believe the problem has been fixed. @VisLab would you mind seeing if it works for you?

**Comment by VisLab** [comment]
Looks good!  Thanks @dungscout96
