### ISSUE TITLE
What schema attributes are inherited?

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#48]
The HED specification is unclear on this point. 

Some attributes such as *extensionAllowed* explicitly say in their descriptions that the property propagates to child tags.

My feeling is that all schema attributes that don't have *unitProperty*, *unitModifierProperty*, or *valueClassProperty* properties (i.e., attributes that apply to the schema proper rather than the auxiliary classes)
should be inherited by child tags. 
**Reasoning:**  the schema nodes in a hierarchy must satisfy "is-a", so it makes sense that they have the attributes.

**Objections to adding this clarification to the HED specification?**

@IanCa How is this handled in the hed-python tools now?

@happy5214 How is this handled in the hed-javascript tools now?

**Comment by IanCa** [comment]
Right now for extension allowed I just explicitly call the following for extension allowed.

(On a tag or schema entry)
self.any_parent_has_attribute(HedKey.ExtensionAllowed)

It wouldn't be hard to do similar for other properties based on some criteria, but might eventually need to be optimized some.  Extension allowed only really comes up in the validator, others might potentially come up more frequently.

**Comment by happy5214** [comment]
The JavaScript validator handles recursion only for `extensionAllowed`, and it does this in two ways, depending on whether the schema is compliant with the HED 2 or HED 3 standard.

For HED 2, the `extensionAllowed` attribute is simply copied down recursively when found.

When I wrote the HED 3 schema parser, I made up my own internal schema attribute (`recursive`) , assigned that `boolProperty` and `attributeProperty`, and gave it to `extensionAllowed`, with the schema parser checking for any attributes with the `recursive` attribute (currently only boolean attributes; that's a bug) and copying them down recursively.

**Comment by VisLab** [comment]
I think the idea of schema attribute inheritance may need to be carefully revisited.  We might need an `inherited` attribute property.

There are several attributes such as `suggestedTag` that I think users would like to be inherited.
Alternatively, annotation tools could just gather all of the parent's `suggestedTag`'s when presenting suggestions for tagging.

Other tags that might need to be inherited are `tagGroup` and `topLevelTagGroup`.
Right now none of these have children as far as I know.

@IanCa @dungscout96 @happy5214 @tpatpa   Could you please comment?  Are there attributes that need to be inherited?

We will need to decide how schema attribute inheritance is handled so that it can be clarified in the specification.

**Comment by happy5214** [comment]
If `suggestedTag` is to be heritable, then `relatedTag` ought to be as well.

Another use case is for attributes like `unique` (but probably not `required`), `recommended` (to the extent that it will be used in the future), `valueClass`, and `unitClass` on parent tags of groups where all child/leaf nodes (as applicable) share the same values for those attributes. Note that the JavaScript validator should treat a node with `unitClass` but without `takesValue` as a valueless tag (i.e. it should ignore `unitClass`), and `valueClass` hasn't been implemented yet.

Is `inherited` (which would replace `recursive` in the JavaScript validator) going to be an attribute itself, as suggested in https://github.com/hed-standard/hed-specification/issues/428, or a property? All of the current properties have a type component, either in their allowed element usage or their assigned values, and inheritance doesn't fit into that paradigm.

**Comment by VisLab** [comment]
> All of the current properties have a type component, either in their allowed element usage or their assigned values, and inheritance doesn't fit into that paradigm.

Yes `inherited` would be a schema property.  We have been discussing adding a property that indicates the attribute applies to everything.  The current behavior is that things that don't have another "type" property apply to "node". 
That would still apply, but we would add another "type" property which ways that it applies to everything.
We would also allow multiple type properties to apply.

> If suggestedTag is to be heritable, then relatedTag ought to be as well.

Yes `relatedTag` would be handled in the same way as `suggestedTag`.

**Comment by tpatpa** [comment]
`suggestedTag` is extensively used in HED-SCORE and is mostly applied to child nodes.
Adding an `inherited` schema attribute could simplify schema development in certain cases allowing to indicate the attribute applies to everything instead of repeating in all child nodes.

**Comment by happy5214** [comment]
> > All of the current properties have a type component, either in their allowed element usage or their assigned values, and inheritance doesn't fit into that paradigm.
> 
> Yes `inherited` would be a schema property. We have been discussing adding a property that indicates the attribute applies to everything. The current behavior is that things that don't have another "type" property apply to "node". That would still apply, but we would add another "type" property which ways that it applies to everything. We would also allow multiple type properties to apply.

I'm struggling to see the connection between `inherited` and the "catch-all" type property you mentioned. Inheritance of a schema attribute by child elements isn't an aspect of an attribute's type. The way I see it, properties are checked at "compile-time" (i.e. schema validation) to ensure that the schema attributes comply with proper usage (with current properties, those would be their allowed modified elements and their value/boolean type). Attribute inheritance is a strictly run-time (i.e. validation or search) notion, unless I'm missing something.

**Comment by happy5214** [comment]
I'll also add (this is unrelated to the above post) that the JavaScript validator explicitly only supports the two kinds of properties currently in use, the ones defining element type and value data type. It references them as the `categoryProperty` and `typeProperty` fields in each `SchemaAttribute` object.

**Comment by VisLab** [comment]
The `isInherited` property has been added in schema version 8.2.0.  How inheritance of attributes will be handled is not completely clear at this time and will be addressed in the future.
