### ISSUE TITLE
Proposal: A library schema should be associated with a standard schema

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#52]
Each library schema would be associated with a  specified version of the standard schema.

**Proposed syntax:**

> mediawiki:   HED library="score" version="0.0.1"  with-version="8.1.0"

> xml:  \<HED library="score" version="0.0.1" with-version="8.1.0"\>

**Justification:**

1.  This would solve the issue of conflicts with special mean tags like *Definition* (See issue #50).

2.  Tags could just specify    "HEDVersion": "score_0.0.1" and both schemas would be loaded and no sc: type tag prefixes required.
(This would still allow another version of HED to be used with the prefix.)

3.  The viewers could give users the option seeing just the library or seeing the two schemas interleaved.

4.  The schema creators could add to children to nodes in the standard schema, but they would have to have the same path as the standard schema:     ie:    *Item/Biological-item/Organism/Virus* could be added to the library, but an existing tag in the sibling standard schema could not be added.

5.  The schema attributes and unit classes from the sibling parent schema would be assumed and not need to be repeated.

Would like comments:   @dorahermes @tpatpa @dungscout96 @IanCa @happy5214

**Comment by IanCa** [comment]
I don't quite understand how this will resolve different namespaces.

As a convoluted example:
we load the following 3 schemas while validating/analyzing a file:
Base schema 8.0.0
Library schema: sc:score_0.0.1 -> References base schema 8.1.0
Library Schema2: mv:movie_0.0.1 -> references base schema 8.2.0

Definition/ is now there 3 times(in 8.0, in score as 8.1, and movie as 8.2).  How do we know which version of Definition is being referenced at any given time if it doesn't have a prefix?  How do we plan to merge/ignore such conflicts?

Is it just illegal to use schemas with different standard schemas at the same time?  Previously these conflicts weren't possible since all tags had prefixes and all schemas were self contained.

I may be misunderstanding how associated schemas work.

**Comment by VisLab** [comment]
There is only one Definition --- associated with the first item in the list
of three.

The others will appear in the annotations as sc:Definition and
mv:Definition.

**Comment by dungscout96** [comment]
This approach requires that library schema and base schema don't have overlapping terms (Otherwise justification #2 wouldn't apply). In such case wouldn't we not worried about library schemas duplicate special tags in base schema with different meaning already?
If terms in base schema and library schema are all unique, we can already achieve the features in justification #2 and #3. We might still want to allow term duplication between library schemas however.

I don't quite get justification #4 and #5.

**Comment by VisLab** [comment]
> This approach requires that library schema and base schema don't have overlapping terms (Otherwise justification no. 2 wouldn't apply). In such case wouldn't we not worried about library schemas duplicate special tags in base schema with different meaning already? 

The fundamental problem here is that terms in the base schema will change over time. It is impossible for any library schema to assure that it does not overlap terms without know which schema it does not overlap.

If we adopt this, the schema validators would automatically detect the overlaps and not validate if there was an issue.

> We might still want to allow term duplication between library schemas however.
Library schemas don't know about other schemas --- they can duplicate each other as much as they want and there will be no problem with the tools.


> I don't quite get justification no. 4 and 5.
This is not an integral part of the proposal. We would just have to decide how to handle these issues.

**Comment by happy5214** [comment]
While we're at it, why don't we just support importing arbitrary HED schemas into a library schema?

As a theoretical example (and, yes, taking scans of numismatists looking at money is a valid use case), take a library schema representing currencies. If the maintainers of that schema decline to include certain kinds of currencies, for example obsolete/historical currencies or cryptocurrencies, an extension library schema could be made to include those. Especially in the first case, as an example, ancient Roman currency (to my knowledge) doesn't have an ISO 4217 code, so a simple catch-all value-taking tag keyed on those codes wouldn't work. However, it would be wasteful to duplicate the tags defined in the original currency library schema for the "additional currencies" extension.

The imports would be of specific schema name/version pairs, either in the same format as the import strings or encoded in two-subelement XML elements (except for the standard schema, which would have a different element name and only one subelement for the version), all encapsulated in some sort of `schemaImports` section.

There are five possible solutions to name conflicts:

1. Silently mask conflicting names, only using the name defined in the directly imported schema.
2. Mask conflicting names as above, but warn at validation time.
3. Error out at validation time.
4. Error out at schema generation time (i.e. MediaWiki -> XML).
5. Reference conflicting names via sub-namespaces:
    - Add a second/third subelement to the imports defining a tag namespace for the imports _or_ use a standardized form based on the schema ID and version number.
    - Reference any conflicts as follows: `import/nestedimport:Tag` or `/nestedimport:Tag`
    - Non-conflicting names could be referenced with or without the sub-namespace, but referencing a conflicting name without the sub-namespace will be an error.

Version conflicts would be an issue with this overall idea, especially with different library schemas along the chain requiring different standard schemas.

**Comment by tpatpa** [comment]
I like the idea of associating each library schema with a standard schema. 
Two things I though about based on my experience when developing the HED-SCORE schema library were already discussed above.

1. Multiple standard schemas associated within one file being tagged:
> As a convoluted example: we load the following 3 schemas while validating/analyzing a file: Base schema 8.0.0 Library schema: sc:score_0.0.1 -> References base schema 8.1.0 Library Schema2: mv:movie_0.0.1 -> references base schema 8.2.0
> 
> So if the score library, loaded as prefix sc:, wants to reference definition from it's standard schema), it will now have to use sc:Definition/?

I also had a similar example to the one @IanCa presented jump to my mind. thinking it could become quite complicated when each library schema is associated with a different standard schema... BUT as @VisLab pointed out, with the prefix, things are made very clear!

2. Tools to properly validate:
> The fundamental problem here is that terms in the base schema will change over time. It is impossible for any library schema to assure that it does not overlap terms without know which schema it does not overlap.
> 
> If we adopt this, the schema validators would automatically detect the overlaps and not validate if there was an issue.

in developing the HED-SCORE schema library, I avoided overlap terms with the standard schema by manually searching the schema. Adding this to the validator would be fantastic!

**Comment by IanCa** [comment]
I kind of like happy5214 suggestion, but I'd probably say we just disallow having different base schemas without prefixes if we do it.  If you want to use an out of date library schema with a different updated library schema, I think it's reasonable one of those have a prefix.

People could get a similar effect by manually combining two libraries and using the combined one under the original proposal though.

The original proposal seems good/workable and I don't see any showstoppers with it.

**Comment by happy5214** [comment]
The more I think about my own idea of extending library schemas (as if they had a superclass-subclass relationship), the more I think it violates HED's core orthogonality principle. Semantic data is replete with ontologies redefining the same concepts and then linking to other ontologies' implementations of them.

By referencing the standard schema through the library schema (i.e. through its prefix), we're treating the standard schema as both a standalone schema and as a "bootstrapping" schema for the libraries, in essence an embeddable tag utility "library" for the library schemas. As a programmer, it reminds me of a programming language's standard library (e.g. libc, Java API), and version conflicts abound in that use case too.

**Comment by VisLab** [comment]
**REVISED PROPOSAL**

Each HED library schema would be associated with a  specified version of the HED standard schema.

**Proposed syntax:**

> mediawiki:   HED library="score" version="0.0.1"  with-standard="8.1.0"

> xml:  \<HED library="score" version="0.0.1" with-standard="8.1.0"\>

**Additional rules:**

1. All the extra sections of the standard schema:
    - schema attributes
    - value classes
    - unit classes
    - units
    - unit modifiers
    - properties
would apply to the library schema and would not be repeated in the library schema.
2. The library schema could not reuse any node (tag terms) from the standard schema.
3. The library schema would be free to add additional unit class, unit, schema attribute, and value class elements.
4. The library schema elements could use `relatedTag` and `suggestedTag` values from the standard schema.

**Justification:**

1.  This would solve the issue of conflicts with special mean tags like *Definition* (See issue #50).

2.  Tags could just specify    "HEDVersion": "score_0.0.1" and both schemas would be loaded with just a single version specification.

3.  No  sc: type tag prefixes required for annotation. Thus about 99% of the use-cases would not need tag prefixes. (Another version of HED could still be used with the prefix.)

5.  The viewers could give users the option of seeing just the library or seeing the two schemas interleaved.

6.  The non-overlap of terms would be checked at schema validation time and not need to be checked after the library schema was released.

7.  The schema designers would not have to worry about adding a lot of synonyms for additional useful standard tags in order to take advantage of the  `relatedTag`  and `suggestedTag` attributes, since now related and suggested tags from the standard schema would also be allowed.

Would appreciate any additional comments:   @dorahermes @tpatpa @sappelhoff @arno @monique2208 and of course all others as this is close to being finalized.

**Comment by happy5214** [comment]
> 6. A new schema attribute `library` would be introduced whose value was the name of the library.
> The tags from the library schema would have this tag as would items added in the library schema.
> (This would also probably require the introduction of a `nodeProperty` schema property so that schema attributes
> without one of the other property designations would no longer default to being a node property.

Changing the "null" property semantics from being an implicit `nodeProperty` to an implicit "universal" property would be a breaking change for the validators. Without hard-coding a bunch of version compatibility checks into the validators, we'd have to either create a new property for the catch-all case or allow multiple "type" properties on a single attribute, in both cases deprecating the "null" type property semantic entirely.

**Comment by VisLab** [comment]
Not sure this is the case.  The current rule is that if the schema attribute doesn't have one of `unitClassProperty`, `unitModifierProperty`, `unitProperty` or `valueClassProperty`,  it is assumed to default to `nodeProperty`.
This can stay the same.

Adding `nodeProperty` as an explicit option allows a schema property to apply to multiple elements.
The alternative is to add separate `library` attributes for each type of element. That doesn't seem as clean?

HED validators don't really need to be concerned about this do they?  It would be mainly the schema validator.

**Comment by VisLab** [comment]
Resolved HWG meeting of 4/13/2023.  Library schema will hence forth be required to be partnered with a specific version of the standard schema. The schema header will contain the withStandard=xxx where xxx is the standard schema version:

Example:
HED library="score" version="1.1.0" withStandard="8.2.0"
