### ISSUE TITLE
Allow schemaAttributes to have their own attributes

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-schemas#72]
As I was starting to plan the rewrite of the JavaScript validator's schema XML parsing, I realized that the recursive aspect of the `extensionAllowed` schema attribute was better expressed in the schema itself, rather than being special-cased in the validators. This led me to the idea of allowing attributes to have their own attributes. I think this would have several additional benefits, including:

1. Expressing property types for an attribute would no longer need a special syntax, as they would be expressed as values of a `property` (or similarly named) attribute on the `schemaAttribute` element.
2. This would allow for additional schema validation in the future (one idea is an attribute expressing mutually exclusive attributes that could be applied to `extensionAllowed` and `takesValue`, flagging any schema with a node that uses both as invalid).

**Comment by VisLab** [comment]
Schema attributes have `Properties`.  These are essentially attributes of other elements of the schema, not just schema attributes.

 We are adding the `isInherited` property in HED 8.2.0.

The three schema attributes that will get this property are: `extensionAllowed`, `relatedTag`, and `suggestedTag`.

**Comment by happy5214** [comment]
You know I'm now going to ask for properties to have properties. All
existing properties have some element of typing associated with them,
whether it's their allowed uses or their allowed values. Those aspects will
now need to be represented somehow in order to facilitate automated parsing
by the validator.

**Comment by VisLab** [comment]
I'm going to link this issue to the milestones #78 and close for now.

**Comment by VisLab** [comment]
The mapping to the HED ontology has resolved this.  The Schema Properties section (which contains the attributes for schema attributes has been revampled).  These are not mapped to ontology classes or ontology properties, but rather specify the domain, range and type of property that the schema attributes are mapped into.
